Feature/batching keydra runs
Athena-Home-Loans/keydra pull request #68
Opened 2022-11-15 00:29 UTC by flukesy

Replacing the old secondary keydra nightly rotation option with a batch number and number of batches configuration.  
Previously the secondary keydra rotation option had a hard-coded run of the first 50 secrets then the rest.  
This new option will allow you to specify the number of batches you want to split the rotation into and which batch to process, batch number starts from 0.

e.g. for keydra you can specify
{"trigger": "nightly", batch_number: 0, number_of_batches: 2}
this will split the secrets into 2 batches and run the first batch of secrets

2022-11-15 00:40 UTC, gyrospectre commented
Fix linter issues please.

2022-11-15 01:09 UTC, gyrospectre commented
Suggest this should also include doc updates to explain the new feature(s).

2022-11-15 02:00 UTC, pablogrigo requested changes
Kindly check inline comments.

2022-11-15 02:00 UTC, pablogrigo commented on tests/test_config.py
> +            ("str", "str2"),  # double string
Please separate the tests for the 2 validations (parameter type vs batch numbers checks), and assert the different exception messages using `self.assertRaisesRegex`

2022-11-15 02:00 UTC, pablogrigo commented on tests/test_config.py
> +                    envs["dev"]["secrets"].append(str(secret_id))
The setup performed inside this `for` loop is not required by the test, please remove it

2022-11-15 02:00 UTC, pablogrigo commented on src/keydra/config.py
>              if rotate == 'nightly':
Please merge this second `if` statement into the one in line 131

2022-11-16 03:41 UTC, pablogrigo approved these changes

2022-11-16 03:41 UTC, merged